<?php
define('__GIROCHECKOUT_SDK_DEBUG__',true);

/**
 * Sample code for GiroCheckout integration of a giropay transaction
 *
 * @filesource
 * @package Samples
 * @version $Revision: 176 $ / $Date: 2017-01-09 13:29:27 -0300 (Mon, 09 Jan 2017) $
 */
require_once '../../GiroCheckout_SDK/GiroCheckout_SDK.php';

/**
 * Configuration of the merchants identifier, project and password
 * this information can be found in the GiroCockpit's project settings
 */
$merchantID = 0;        // Your merchant ID (Verkaufer-ID)
$projectID = 0;         // Your project ID (Projekt-ID)
$projectPassword = "";  // Your project password


/* init giropay transaction and parameters */
try {
	$request = new GiroCheckout_SDK_Request('giropayTransaction');
	$request->setSecret($projectPassword);
	$request->addParam('merchantId',$merchantID)
	        ->addParam('projectId',$projectID)
	        ->addParam('merchantTxId',"1234567890")
	        ->addParam('amount',100)
	        ->addParam('currency','EUR')
	        ->addParam('purpose','Beispieltransaktion')
	        //->addParam('bic','TESTDETT421')
	        ->addParam('info1Label','Ihre Kundennummer')
	        ->addParam('info1Text','0815')
	        ->addParam('urlRedirect','https://www.my-domain.de/girocheckout/redirect.php')
	        ->addParam('urlNotify','https://www.my-domain.de/girocheckout/notify.php')

	        //the hash field is auto generated by the SDK
	        ->submit();

  //echo "<pre>";print_r($request->getResponseRaw());echo "</pre>";

	/* if transaction succeeded update your local system an redirect the customer */
	if($request->requestHasSucceeded()) {
    $request->getResponseParam('rc');
    $request->getResponseParam('msg');
    $request->getResponseParam('reference');
    $request->getResponseParam('redirect');

    $request->redirectCustomerToPaymentProvider();
	}
	/* if the transaction did not succeed update your local system, get the responsecode and notify the customer */
	else {
    $request->getResponseParam('rc');
    $request->getResponseParam('msg');
    $request->getResponseMessage($request->getResponseParam('rc'),'DE');
	}
}
catch (Exception $e) {
  echo "Exception: ";
  echo $e->getMessage();
}