<?php
define('__GIROCHECKOUT_SDK_DEBUG__',true);

/**
 * Sample code for GiroCheckout integration of a klarna void/reversal
 *
 * @filesource
 * @package Samples
 * @version $Revision: 274 $ / $Date: 2019-09-06 14:04:44 -0400 (Fri, 06 Sep 2019) $
 */
require '../vendor/autoload.php';
use girosolution\GiroCheckout_SDK\GiroCheckout_SDK_Request;
use girosolution\GiroCheckout_SDK\helper\GiroCheckout_SDK_TransactionType_helper;

/**
 * Configuration of the merchants identifier, project and password
 * this information can be found in the GiroCockpit's project settings
 */
$merchantID = 0;        // Your merchant ID (Verkaufer-ID)
$projectID = 0;         // Your project ID (Projekt-ID)
$projectPassword = "";  // Your project password

/**
 * Specify reference number of the preauthorization transaction that is to be reversed
 */
$strReference = "afbbc62a-c4c3-462b-b1cd-11f7aa9983ff";

/* init klarna void and parameters */
try {
  $request = new GiroCheckout_SDK_Request( GiroCheckout_SDK_TransactionType_helper::TRANS_TYPE_KLARNA_VOID );
  $request->setSecret($projectPassword);

  $request->addParam('merchantId',$merchantID)
          ->addParam('projectId',$projectID)
          ->addParam('merchantTxId',"1234567890123456789012")
          ->addParam('reference', $strReference)

          //the hash field is auto generated by the SDK
          ->submit();

  //echo "<pre>";print_r($request->getResponseRaw());echo "</pre>";

  /* if transaction succeeded update your local system */
  if($request->requestHasSucceeded()) {
        // rc is the response code
        $rc = $request->getResponseParam('rc');

        // This is how you can get the response parameters
        $request->getResponseParam('msg');
        $request->getResponseParam('reference');
  }
  /* if the transaction did not succeed update your local system, get the responsecode and notify the customer */
  else {
        echo $request->getResponseParam('rc') . " " . $request->getResponseParam('msg') . "\n";
  }
}
catch (Exception $e) {
  echo "Exception: <br>";
  echo $e->getMessage();

  echo "<pre>";print_r($request->getResponseRaw());echo "</pre>";
}