<?php
define('__GIROCHECKOUT_SDK_DEBUG__', TRUE);

/**
 * Sample code for GiroCheckout integration of a Google pay refund transaction
 *
 * Call through web server in two steps:
 * 1) Without arguments for initial SALE transaction: http://localhost/GooglePayRefund.php, copy displayed reference
 * 2) With reference code from SALE for REFUND, parameter mode=ref (for refund), parameter ref for reference:
 * http://localhost/GooglePayRefund.php?mode=ref&ref=43290-48329043-43289
 *
 * @filesource
 * @package Samples
 * @version $Revision: 274 $ / $Date: 2019-09-06 14:04:44 -0400 (Fri, 06 Sep 2019) $
 */
require '../vendor/autoload.php';
use girosolution\GiroCheckout_SDK\GiroCheckout_SDK_Request;
use girosolution\GiroCheckout_SDK\helper\GiroCheckout_SDK_TransactionType_helper;

/**
 * Configuration of the merchants identifier, project and password
 * this information can be found in the GiroCockpit's project settings
 */
$merchantID = 0;        // Your merchant ID (Verkaufer-ID)
$projectID = 0;         // Your project ID (Projekt-ID)
$projectPassword = "";  // Your project password

$strReference = "7116eadd-d2af-48fd-ba9d-847f354cf8aa";

if (empty($strReference)) {
  echo "Reference must be given.";
  exit;
}

try {
  $request = new GiroCheckout_SDK_Request(GiroCheckout_SDK_TransactionType_helper::TRANS_TYPE_GOOGLE_PAY_REFUND);
  $request->setSecret($projectPassword);
  $request->addParam('merchantId', $merchantID)
    ->addParam('projectId', $projectID)
    ->addParam('merchantTxId', uniqid())
    ->addParam('amount', 100)
    ->addParam('currency', 'EUR')
    ->addParam('purpose', 'Erstattung Nr. 3')
    ->addParam('reference', $strReference)
    //the hash field is auto generated by the SDK
    ->submit();

  echo "<pre>";
  print_r($request->getResponseRaw());
  echo "</pre><br/>";

  /* if transaction succeeded update your local system and redirect the customer */
  if ($request->requestHasSucceeded()) {
    $request->getResponseParam('reference');
    $strResPay = $request->getResponseParam('resultPayment');
    $request->redirectCustomerToPaymentProvider();
  }
  /* if the transaction did not succeed update your local system, get the responsecode and notify the customer */
  else {
    $request->getResponseParam('rc');
    $request->getResponseParam('msg');
    $request->getResponseMessage($request->getResponseParam('rc'), 'DE');
  }
}
catch (Exception $e) {
  echo $e->getMessage();
  echo "<pre>";print_r($request->getResponseRaw());echo "</pre>";
}
